// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaLearnGo.Models;

#nullable disable

namespace SistemaLearnGo.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241002145847_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaLearnGo.Models.Avaliacao", b =>
                {
                    b.Property<int>("AvaliacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AvaliacaoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvaliacaoId"));

                    b.Property<string>("AvaliacaoComentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<int>("CaronaId")
                        .HasColumnType("int");

                    b.HasKey("AvaliacaoId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("CaronaId");

                    b.ToTable("Avaliacao");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.Cadastro", b =>
                {
                    b.Property<int>("CadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CadastroId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CadastroId"));

                    b.Property<string>("CadastroCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroCurso");

                    b.Property<string>("CadastroDataNascimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroDataNascimento");

                    b.Property<string>("CadastroEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroEmail");

                    b.Property<string>("CadastroEndereço")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroEndereço");

                    b.Property<string>("CadastroNomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroNomeCompleto");

                    b.Property<string>("CadastroRm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroRm");

                    b.Property<string>("CadastroSenha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CadastroSenha");

                    b.Property<int>("FaculdadeId")
                        .HasColumnType("int");

                    b.HasKey("CadastroId");

                    b.HasIndex("FaculdadeId");

                    b.ToTable("Cadastro");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.Carona", b =>
                {
                    b.Property<int>("CaronaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CaronaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaronaId"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<string>("CaronaDestino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CaronaDestino");

                    b.Property<DateTime>("CaronaHorario")
                        .HasColumnType("datetime2")
                        .HasColumnName("CaronaHorario");

                    b.Property<string>("CaronaOrigem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CaronaOrigem");

                    b.Property<int>("CaronaTipoId")
                        .HasColumnType("int");

                    b.Property<string>("CaronaVagas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CaronaVagas");

                    b.Property<string>("CaronaVeiculo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CaronaVeiculo");

                    b.HasKey("CaronaId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("CaronaTipoId");

                    b.ToTable("Carona");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.CaronaHasCadastro", b =>
                {
                    b.Property<int>("CaronaHasCadastroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CaronaHasCadastroId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaronaHasCadastroId"));

                    b.Property<int>("CadastroId")
                        .HasColumnType("int");

                    b.Property<int>("CaronaId")
                        .HasColumnType("int");

                    b.HasKey("CaronaHasCadastroId");

                    b.HasIndex("CadastroId");

                    b.HasIndex("CaronaId");

                    b.ToTable("CaronaHasCadastro");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.CaronaTipo", b =>
                {
                    b.Property<int>("CaronaTipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CaronaTipoId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaronaTipoId"));

                    b.Property<string>("CaronaTipoDescricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CaronaTipoDescricao");

                    b.HasKey("CaronaTipoId");

                    b.ToTable("CaronaTipo");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.Faculdade", b =>
                {
                    b.Property<int>("FaculdadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FaculdadeId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaculdadeId"));

                    b.Property<string>("FaculdadeCidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FaculdadeCidade");

                    b.Property<string>("FaculdadeNome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FaculdadeNome");

                    b.HasKey("FaculdadeId");

                    b.ToTable("Faculdade");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.Avaliacao", b =>
                {
                    b.HasOne("SistemaLearnGo.Models.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLearnGo.Models.Carona", "Carona")
                        .WithMany()
                        .HasForeignKey("CaronaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");

                    b.Navigation("Carona");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.Cadastro", b =>
                {
                    b.HasOne("SistemaLearnGo.Models.Faculdade", "Faculdade")
                        .WithMany()
                        .HasForeignKey("FaculdadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculdade");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.Carona", b =>
                {
                    b.HasOne("SistemaLearnGo.Models.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLearnGo.Models.CaronaTipo", "CaronaTipo")
                        .WithMany()
                        .HasForeignKey("CaronaTipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");

                    b.Navigation("CaronaTipo");
                });

            modelBuilder.Entity("SistemaLearnGo.Models.CaronaHasCadastro", b =>
                {
                    b.HasOne("SistemaLearnGo.Models.Cadastro", "Cadastro")
                        .WithMany()
                        .HasForeignKey("CadastroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaLearnGo.Models.Carona", "Carona")
                        .WithMany()
                        .HasForeignKey("CaronaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadastro");

                    b.Navigation("Carona");
                });
#pragma warning restore 612, 618
        }
    }
}
